# tasks file for verapdf.logius
---
- name: Create verapdf group
  group:
    name: "{{ verapdf_linux_group }}"
    state: present

- name: Create logius user
  user:
    name: "{{ verapdf_linux_user }}"
    groups:
      - "{{ verapdf_linux_group }}"
    createhome: no
    system: yes

- name: Download and unpack the latest verapdf release package
  unarchive:
    src: "{{ verapdf_download_url }}"
    dest: "{{ verapdf_tmp_root }}"
    remote_src: True
    creates: "{{ verapdf_tmp_installer_dir }}"
  tags:
      - "update-vera"

- name: Add the autoinstall XML file from a template
  template:
    src: "tmp/verapdf/verapdf-install.xml.j2"
    dest: "{{ verapdf_tmp_installer_dir }}/verapdf-install.xml"
    owner: "{{ verapdf_linux_user }}"
    group: "{{ verapdf_linux_group }}"
    mode: 0775
  tags:
      - "update-vera"

- name: Run veraPDF installer
  command: "java -jar {{ verapdf_installer_jar }} {{ verapdf_tmp_installer_dir }}/verapdf-install.xml"
  tags:
      - "update-vera"

- name: Overwrite features congiguration
  template:
    src: "verapdf/config/features.xml.j2"
    dest: "{{ verapdf_install_dest }}/config/features.xml"
    owner: "{{ verapdf_linux_user }}"
    group: "{{ verapdf_linux_group }}"
    mode: 0775
  tags:
      - "update-vera"

- name: Set ownership of veraPDF installation
  file:
    path: "{{ verapdf_install_dest }}"
    owner: "{{ verapdf_linux_user }}"
    group: "{{ verapdf_linux_group }}"
    mode: 0775
    recurse: yes
  tags:
      - "update-vera"
