# tasks file for verapdf.logius
---
- name: Create logius group
  group:
    name: "{{ logius_linux_group }}"
    state: present

- name: Create logius user
  user:
    name: "{{ logius_linux_user }}"
    groups:
      - "{{ logius_linux_group }}"
    createhome: no
    system: yes

- name: Clone git repository
  git:
    repo: "{{ logius_git_url }}"
    dest: "{{ logius_git_root }}"
    version: "{{ logius_git_branch }}"
    update: "{{ logius_git_update }}"

- name: Build Maven project
  command: mvn clean package
  args:
    chdir: "{{ logius_git_root }}"
    creates: "{{ logius_git_root }}/LogiusWebApp/target/LogiusWebApp-1.0-SNAPSHOT.jar"

- name: Create application install directory
  file:
    path: "{{ logius_app_home }}/{{ item }}"
    state: directory
    owner: "{{ logius_linux_user }}"
    group: "{{ logius_linux_group }}"
    mode: "755"
  with_items:
    - "bin"
    - "config"
    - "resources"

- name: Create application log directory
  file:
    path: "{{ logius_log_dir }}"
    state: directory
    owner: "{{ logius_linux_user }}"
    group: "{{ logius_linux_group }}"
    mode: "744"
  with_items:
    - "bin"
    - "config"
    - "resources"

- name: Copy application sample report
  copy:
    src: "{{ logius_git_root }}/LogiusWebApp/src/main/resources/{{ item }}"
    remote_src: true
    dest: "{{ logius_app_resources }}/{{ item }}"
    owner: "{{ logius_linux_user }}"
    group: "{{ logius_linux_group }}"
    mode: "755"
  with_items:
    - "sample_report.ods"

- name: Add Web app configuration templates
  template:
    src: "var/lib/logius/resources/{{ item }}.j2"
    dest: "{{ logius_app_resources }}/{{ item }}"
    owner: "{{ logius_linux_user }}"
    group: "{{ logius_linux_group }}"
    mode: 0775
  with_items:
    - "sample_configuration.cxml"

- name: Deploy application jars
  copy:
    src: "{{ logius_git_root }}/{{ item.src_dir }}/target/{{ item.src_file }}"
    remote_src: true
    dest: "{{ item.dest_dir }}/{{ item.dest_file }}"
    owner: "{{ logius_linux_user }}"
    group: "{{ logius_linux_group }}"
    mode: "755"
  with_items:
    - { src_dir: "LogiusWebApp", src_file: "LogiusWebApp-1.0-SNAPSHOT.jar", dest_dir: "{{ logius_app_bin }}", dest_file: "web-app-1.0.jar" }
    - { src_dir: "VeraPDFService", src_file: "VeraPDFService-1.0-SNAPSHOT.jar", dest_dir: "{{ logius_app_bin }}", dest_file: "verapdf-service-1.0.jar" }
    - { src_dir: "SampleWebApp", src_file: "SampleWebApp-1.0-SNAPSHOT.jar", dest_dir: "{{ logius_app_bin }}", dest_file: "sample-web-app-1.0.jar" }
    - { src_dir: "HeritrixExtention", src_file: "HeritrixExtention.jar", dest_dir: "{{ logius_heritrix_home }}/lib", dest_file: "logius-heritrix-extenstion.jar" }

- name: Add Web app configuration templates
  template:
    src: "var/lib/logius/config/{{ item }}.yml.j2"
    dest: "{{ logius_app_config }}/{{ item }}.yml"
    owner: "{{ logius_linux_user }}"
    group: "{{ logius_linux_group }}"
    mode: 0644
  with_items:
    - "web-app"
    - "sample-web-app"
    - "verapdf-service"

- name: Add Web app startup script
  template:
    src: "var/lib/logius/{{ item }}.sh.j2"
    dest: "{{ logius_app_home }}/{{ item }}.sh"
    owner: "{{ logius_linux_user }}"
    group: "{{ logius_linux_group }}"
    mode: 0755
  with_items:
    - "run"
    - "run-heritrix"

- name: Create app DB Schema
  mysql_db:
    state: import
    name: "logius"
    target: "{{ logius_git_root }}/LogiusWebApp/src/main/resources/schema.sql"

- name: Remove default nginx site
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
